# Generated by Django 5.0.7 on 2024-07-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_atendente_appbanco_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appbanco',
            name='aceita_whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
