# Generated by Django 5.1.7 on 2025-04-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appbanco_aceita_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='appbanco',
            name='insta',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appbanco',
            name='nome_lider',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
