# Generated by Django 5.1.7 on 2025-04-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appbanco_insta_appbanco_nome_lider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appbanco',
            name='aceita_whatsapp',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='SIM', max_length=3),
        ),
    ]
